#pragma once

//Every type of event the engine can create
//max is used as the last one so that the total amount of events can be found easily
const enum class EventType {
	EVENT_QUIT,
	EVENT_MOVE_ENTITY,
	EVENT_ROTATE_ENTITY,
	EVENT_ENTITY_JUMP,
	EVENT_PLAY_MUSIC,
	EVENT_PLAY_FX,
	EVENT_MUSIC_VOLUME,
	EVENT_CREATE_OBJECT,
	EVENT_CREATE_OBJECT_ENTITY,
	EVENT_CREATE_PLAYER,
	EVENT_CREATE_PLAYER_ENTITY,
	EVENT_CREATE_LIGHT,
	EVENT_CREATE_LIGHT_ENTITY,
	EVENT_SEND_MODEL_PATHS,
	EVENT_SEND_AUDIO_PATHS,
	EVENT_CONNECT_CLIENT,
	EVENT_DISCONNECT_CLIENT,
	EVENT_PING_SERVER,
	EVENT_SEND_PACKET,
	max
};